apiVersion: michelangelo.api/v2
kind: Project
metadata:
  name: california-housing
  namespace: california-housing
spec:
  description: "Michelangelo California Housing Examples"
  owner:
    owningTeam: "00000000-0000-0000-0000-000000000001"
    owners:
      - michelangelo-example
    ownerGroups:
      - michelangelo-example
  tier: 4
  gitRepo: https://github.com/michelangelo-ai/michelangelo-examples
  rootDir: src/michelangelo_examples/california_housing
